jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - template: azure-install-rust.yml
    parameters:
      platform: ${{parameters.name}}
      rust_version: stable
  - bash: |
      export CI=True
      cargo test --all
    env:
      LOOM_MAX_DURATION: 10
